### ISSUE TITLE
404 page rendering error when users change the /post/id of the route

### ISSUE THREAD

**Issue by Debagnik** [Debagnik/project-walnut#49]
Steps to reproduce:
1. open home page
2. direct to post page
3. change the ID of the post with a non existing ID.
4. Observe the rendering error in 404 page.

Expected: The 404 page should render when user hits.
Actual: The 404 page is not rendering.

![image](https://github.com/user-attachments/assets/584f0399-b801-4476-b77e-0aebffa0aa5d)

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the error handling in the GET /post/:id route to properly render the 404 page when a post is not found. This ensures that when a user tries to access a non-existent post ID, they will see the custom 404 page instead of a rendering error.

You can review changes in this commit: https://github.com/jjyutm4532/Debagnik-project-walnut-49/commit/70e9850a214156f1fde9c416bdda65bbef32dd9e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Debagnik** [comment]
@jjyutm4532 its not the correct solution tho in PR #50 . I have already solved the issue.

**Comment by Debagnik** [comment]
@Debdaru07 please test this on 1/12/24
